### ISSUE TITLE
How do we handle new linux versions?

### ISSUE THREAD

**Issue by Hunter1753** [openbouffalo/linux#13]
The upsteam torvalds/linux is now on linux 6.3 and the main branch here is on some 6.2 release candidate state

Would there be a reason to try to stay up to date once the drivers are upsteamed?

**Comment by alexhorner** [comment]
> The upsteam torvalds/linux is now on linux 6.3 and the main branch here is on some 6.2 release candidate state
> 
> Would there be a reason to try to stay up to date once the drivers are upsteamed?

Please see #1
